FROM node:buster-slim

SHELL ["/bin/bash", "-ex"]

RUN apt-get update \
    && apt-get install -y git python

RUN cd ~ \
    && git clone https://github.com/Tsuk1ko/cq-picsearcher-bot.git \
    && cd cq-picsearcher-bot \
    && cp config.default.jsonc config.jsonc \